insert into clase (codigo, nombre, region) values (1, 'Fabaceae', 'Na Chaluai');
insert into clase (codigo, nombre, region) values (2, 'Salicaceae', '‘Attīl');
insert into clase (codigo, nombre, region) values (3, 'Parmeliaceae', 'Gonbad-e Kāvūs');
insert into clase (codigo, nombre, region) values (4, 'Nymphaeaceae', 'Seara');
insert into clase (codigo, nombre, region) values (5, 'Rubiaceae', 'Dębów');
insert into clase (codigo, nombre, region) values (6, 'Asteraceae', 'Pasrukrajan Satu');
insert into clase (codigo, nombre, region) values (7, 'Amblystegiaceae', 'Maymana');
insert into clase (codigo, nombre, region) values (8, 'Parmeliaceae', 'København');
insert into clase (codigo, nombre, region) values (9, 'Rubiaceae', 'Nixi');
insert into clase (codigo, nombre, region) values (10, 'Caryophyllaceae', 'Santo Estêvão');
insert into clase (codigo, nombre, region) values (11, 'Polygonaceae', 'Masvingo');
insert into clase (codigo, nombre, region) values (12, 'Asteraceae', 'Dangjiaxian');
insert into clase (codigo, nombre, region) values (13, 'Cyperaceae', 'Pangkalan');
insert into clase (codigo, nombre, region) values (14, 'Asteraceae', 'Angra dos Reis');
insert into clase (codigo, nombre, region) values (15, 'Cactaceae', 'Hongjiang');
insert into clase (codigo, nombre, region) values (16, 'Cactaceae', 'Youxikou');
insert into clase (codigo, nombre, region) values (17, 'Solanaceae', 'Kotri');
insert into clase (codigo, nombre, region) values (18, 'Fabaceae', 'Saint-Rémy-de-Provence');
insert into clase (codigo, nombre, region) values (19, 'Rosaceae', 'Ceuta');
insert into clase (codigo, nombre, region) values (20, 'Gentianaceae', 'Amarillo');
insert into clase (codigo, nombre, region) values (21, 'Fabaceae', 'Brive-la-Gaillarde');
insert into clase (codigo, nombre, region) values (22, 'Anthocerotaceae', 'Opatowiec');
insert into clase (codigo, nombre, region) values (23, 'Saxifragaceae', 'Doushan');
insert into clase (codigo, nombre, region) values (24, 'Asteraceae', 'Caratinga');
insert into clase (codigo, nombre, region) values (25, 'Oleaceae', 'Gulao');
insert into clase (codigo, nombre, region) values (26, 'Orchidaceae', 'Uppsala');
insert into clase (codigo, nombre, region) values (27, 'Onagraceae', 'Fox Creek');
insert into clase (codigo, nombre, region) values (28, 'Rosaceae', 'Yeroẖam');
insert into clase (codigo, nombre, region) values (29, 'Boraginaceae', 'Novosemeykino');
insert into clase (codigo, nombre, region) values (30, 'Parmeliaceae', 'Spitak');
insert into clase (codigo, nombre, region) values (31, 'Asteraceae', 'Klippan');
insert into clase (codigo, nombre, region) values (32, 'Dryopteridaceae', 'Nhà Bàng');
insert into clase (codigo, nombre, region) values (33, 'Sapotaceae', 'Jalal-Abad');
insert into clase (codigo, nombre, region) values (34, 'Liliaceae', 'Si Sa Ket');
insert into clase (codigo, nombre, region) values (35, 'Fabaceae', 'Dordrecht');
insert into clase (codigo, nombre, region) values (36, 'Scrophulariaceae', 'Ágio Pnévma');
insert into clase (codigo, nombre, region) values (37, 'Apocynaceae', 'Daliang');
insert into clase (codigo, nombre, region) values (38, 'Acanthaceae', 'Banyulegi');
insert into clase (codigo, nombre, region) values (39, 'Brassicaceae', 'Boissy-Saint-Léger');
insert into clase (codigo, nombre, region) values (40, 'Asteraceae', 'Sosnovyy Bor');
insert into clase (codigo, nombre, region) values (41, 'Acanthaceae', 'Hongshan');
insert into clase (codigo, nombre, region) values (42, 'Scrophulariaceae', 'Wudui');
insert into clase (codigo, nombre, region) values (43, 'Brassicaceae', 'Vesoul');
insert into clase (codigo, nombre, region) values (44, 'Sapotaceae', 'Yushan');
insert into clase (codigo, nombre, region) values (45, 'Asteraceae', 'Yingzhou');
insert into clase (codigo, nombre, region) values (46, 'Fabaceae', 'Bofuer');
insert into clase (codigo, nombre, region) values (47, 'Poaceae', 'Hołoby');
insert into clase (codigo, nombre, region) values (48, 'Sapindaceae', 'Telaga');
insert into clase (codigo, nombre, region) values (49, 'Araceae', 'Toulouse');
insert into clase (codigo, nombre, region) values (50, 'Polygonaceae', 'Georgīevka');
insert into clase (codigo, nombre, region) values (51, 'Poaceae', 'Caxias');
insert into clase (codigo, nombre, region) values (52, 'Fabaceae', 'Älmhult');
insert into clase (codigo, nombre, region) values (53, 'Myrtaceae', 'Hualfín');
insert into clase (codigo, nombre, region) values (54, 'Asteraceae', 'Huanghai');
insert into clase (codigo, nombre, region) values (55, 'Sapindaceae', 'Savski Venac');
insert into clase (codigo, nombre, region) values (56, 'Iridaceae', 'Nadi');
insert into clase (codigo, nombre, region) values (57, 'Poaceae', 'El Nido');
insert into clase (codigo, nombre, region) values (58, 'Caryophyllaceae', 'Hanting');
insert into clase (codigo, nombre, region) values (59, 'Coniocybaceae', 'São Sepé');
insert into clase (codigo, nombre, region) values (60, 'Asteraceae', 'Heshan');
insert into clase (codigo, nombre, region) values (61, 'Rosaceae', 'Gizałki');
insert into clase (codigo, nombre, region) values (62, 'Fabaceae', 'Tegalheras');
insert into clase (codigo, nombre, region) values (63, 'Boraginaceae', 'Stettler');
insert into clase (codigo, nombre, region) values (64, 'Caprifoliaceae', 'Chão de Couce');
insert into clase (codigo, nombre, region) values (65, 'Celastraceae', 'Káto Miliá');
insert into clase (codigo, nombre, region) values (66, 'Scrophulariaceae', 'Tiguha');
insert into clase (codigo, nombre, region) values (67, 'Boraginaceae', 'Licheng');
insert into clase (codigo, nombre, region) values (68, 'Poaceae', 'Popova');
insert into clase (codigo, nombre, region) values (69, 'Fabaceae', 'Gafanha de Aquém');
insert into clase (codigo, nombre, region) values (70, 'Crossosomataceae', 'Temirtau');
insert into clase (codigo, nombre, region) values (71, 'Polemoniaceae', 'Basa');
insert into clase (codigo, nombre, region) values (72, 'Podocarpaceae', 'Torrão');
insert into clase (codigo, nombre, region) values (73, 'Apiaceae', 'Marco de Canaveses');
insert into clase (codigo, nombre, region) values (74, 'Saxifragaceae', 'Dera Murād Jamāli');
insert into clase (codigo, nombre, region) values (75, 'Asteraceae', 'Bogo');
insert into clase (codigo, nombre, region) values (76, 'Asteraceae', 'Pili');
insert into clase (codigo, nombre, region) values (77, 'Polypodiaceae', 'Dongxi');
insert into clase (codigo, nombre, region) values (78, 'Caryophyllaceae', 'Bergen');
insert into clase (codigo, nombre, region) values (79, 'Chenopodiaceae', 'Ardabīl');
insert into clase (codigo, nombre, region) values (80, 'Fabaceae', 'Betioky');
insert into clase (codigo, nombre, region) values (81, 'Asteraceae', 'Petropavlovskaya');
insert into clase (codigo, nombre, region) values (82, 'Parmeliaceae', 'Haparanda');
insert into clase (codigo, nombre, region) values (83, 'Cupressaceae', 'Mexico');
insert into clase (codigo, nombre, region) values (84, 'Tiliaceae', 'Maştağa');
insert into clase (codigo, nombre, region) values (85, 'Campanulaceae', 'Itaparica');
insert into clase (codigo, nombre, region) values (86, 'Rubiaceae', 'Vällingby');
insert into clase (codigo, nombre, region) values (87, 'Lichinaceae', 'Tongjing');
insert into clase (codigo, nombre, region) values (88, 'Orchidaceae', 'Reno');
insert into clase (codigo, nombre, region) values (89, 'Poaceae', 'Onsala');
insert into clase (codigo, nombre, region) values (90, 'Campanulaceae', 'La Tebaida');
insert into clase (codigo, nombre, region) values (91, 'Poaceae', 'Saint Joseph');
insert into clase (codigo, nombre, region) values (92, 'Pinaceae', 'Hernani');
insert into clase (codigo, nombre, region) values (93, 'Boraginaceae', 'Obolensk');
insert into clase (codigo, nombre, region) values (94, 'Polygonaceae', 'Cesson');
insert into clase (codigo, nombre, region) values (95, 'Fabaceae', 'Mikulintsy');
insert into clase (codigo, nombre, region) values (96, 'Asteraceae', 'Sebewe');
insert into clase (codigo, nombre, region) values (97, 'Fabaceae', 'Lyublino');
insert into clase (codigo, nombre, region) values (98, 'Asteraceae', 'Lailunggi');
insert into clase (codigo, nombre, region) values (99, 'Rosaceae', 'Hutou');
insert into clase (codigo, nombre, region) values (100, 'Lamiaceae', 'Etten-Leur');
insert into clase (codigo, nombre, region) values (101, 'Apiaceae', 'Khorol');
insert into clase (codigo, nombre, region) values (102, 'Parmeliaceae', 'Mellieħa');
insert into clase (codigo, nombre, region) values (103, 'Arthoniaceae', 'Alvesta');
insert into clase (codigo, nombre, region) values (104, 'Asteraceae', 'Luqiao');
insert into clase (codigo, nombre, region) values (105, 'Rhamnaceae', 'Huangni');
insert into clase (codigo, nombre, region) values (106, 'Poaceae', 'Praya');
insert into clase (codigo, nombre, region) values (107, 'Brassicaceae', 'Metković');
insert into clase (codigo, nombre, region) values (108, 'Asclepiadaceae', 'Rājshāhi');
insert into clase (codigo, nombre, region) values (109, 'Malvaceae', 'Borlänge');
insert into clase (codigo, nombre, region) values (110, 'Parmeliaceae', 'Jermenovci');
insert into clase (codigo, nombre, region) values (111, 'Scrophulariaceae', 'Cimanggu');
insert into clase (codigo, nombre, region) values (112, 'Portulacaceae', 'Shumyachi');
insert into clase (codigo, nombre, region) values (113, 'Rubiaceae', 'Sobhādero');
insert into clase (codigo, nombre, region) values (114, 'Fabaceae', 'Tsu-shi');
insert into clase (codigo, nombre, region) values (115, 'Euphorbiaceae', 'Perico');
insert into clase (codigo, nombre, region) values (116, 'Onagraceae', 'Jetak');
insert into clase (codigo, nombre, region) values (117, 'Anthocerotaceae', 'Ardabīl');
insert into clase (codigo, nombre, region) values (118, 'Apiaceae', 'Porecatu');
insert into clase (codigo, nombre, region) values (119, 'Parmeliaceae', 'La Concepción');
insert into clase (codigo, nombre, region) values (120, 'Fabaceae', 'Gândara de Aquém');
insert into clase (codigo, nombre, region) values (121, 'Ephedraceae', 'Melioratyvne');
insert into clase (codigo, nombre, region) values (122, 'Lycopodiaceae', 'Muesanaik');
insert into clase (codigo, nombre, region) values (123, 'Caryophyllaceae', 'Jianshan');
insert into clase (codigo, nombre, region) values (124, 'Apiaceae', 'Krajan Jamprong');
insert into clase (codigo, nombre, region) values (125, 'Rosaceae', 'Tietê');
insert into clase (codigo, nombre, region) values (126, 'Taxaceae', 'Saint-Brieuc');
insert into clase (codigo, nombre, region) values (127, 'Poaceae', 'Barra do Bugres');
insert into clase (codigo, nombre, region) values (128, 'Saxifragaceae', 'Banamba');
insert into clase (codigo, nombre, region) values (129, 'Xyridaceae', 'Moyamba');
insert into clase (codigo, nombre, region) values (130, 'Poaceae', 'Voskopojë');
insert into clase (codigo, nombre, region) values (131, 'Annonaceae', 'Lubomierz');
insert into clase (codigo, nombre, region) values (132, 'Juncaceae', 'Carolina');
insert into clase (codigo, nombre, region) values (133, 'Rutaceae', 'Drakino');
insert into clase (codigo, nombre, region) values (134, 'Orchidaceae', 'Pincher Creek');
insert into clase (codigo, nombre, region) values (135, 'Betulaceae', 'Kubangsari');
insert into clase (codigo, nombre, region) values (136, 'Polemoniaceae', 'Gaoyao');
insert into clase (codigo, nombre, region) values (137, 'Gentianaceae', 'Knivsta');
insert into clase (codigo, nombre, region) values (138, 'Poaceae', 'Stockton');
insert into clase (codigo, nombre, region) values (139, 'Portulacaceae', 'Pining');
insert into clase (codigo, nombre, region) values (140, 'Asteraceae', 'Maria Cristina');
insert into clase (codigo, nombre, region) values (141, 'Boraginaceae', 'Krajan Dua Patempuran');
insert into clase (codigo, nombre, region) values (142, 'Caryophyllaceae', 'Untolovo');
insert into clase (codigo, nombre, region) values (143, 'Arthoniaceae', 'Putrajaya');
insert into clase (codigo, nombre, region) values (144, 'Sapindaceae', 'Kelo');
insert into clase (codigo, nombre, region) values (145, 'Cladoniaceae', 'Fiães');
insert into clase (codigo, nombre, region) values (146, 'Sapotaceae', 'Qingxi');
insert into clase (codigo, nombre, region) values (147, 'Dicranaceae', 'Pilang');
insert into clase (codigo, nombre, region) values (148, 'Caprifoliaceae', 'Cikadondongdesa');
insert into clase (codigo, nombre, region) values (149, 'Polemoniaceae', 'Ciawitali');
insert into clase (codigo, nombre, region) values (150, 'Asteraceae', 'Jiujie');
insert into clase (codigo, nombre, region) values (151, 'Rosaceae', 'Minggang');
insert into clase (codigo, nombre, region) values (152, 'Euphorbiaceae', 'Yanzhou');
insert into clase (codigo, nombre, region) values (153, 'Lichenotheliaceae', 'Ogawa');
insert into clase (codigo, nombre, region) values (154, 'Orobanchaceae', 'Zhangjia');
insert into clase (codigo, nombre, region) values (155, 'Rubiaceae', 'Rosmalen');
insert into clase (codigo, nombre, region) values (156, 'Asteraceae', 'Baiqi');
insert into clase (codigo, nombre, region) values (157, 'Collemataceae', 'Levandeira');
insert into clase (codigo, nombre, region) values (158, 'Teloschistaceae', 'Marne-la-Vallée');
insert into clase (codigo, nombre, region) values (159, 'Cuscutaceae', 'Baddomalhi');
insert into clase (codigo, nombre, region) values (160, 'Asteraceae', 'Khanino');
insert into clase (codigo, nombre, region) values (161, 'Cyperaceae', 'Bambas');
insert into clase (codigo, nombre, region) values (162, 'Solanaceae', 'Boafeo');
insert into clase (codigo, nombre, region) values (163, 'Araliaceae', 'Jaboatão');
insert into clase (codigo, nombre, region) values (164, 'Xyridaceae', 'São Bento');
insert into clase (codigo, nombre, region) values (165, 'Droseraceae', 'Nisporeni');
insert into clase (codigo, nombre, region) values (166, 'Lycopodiaceae', 'Biên Hòa');
insert into clase (codigo, nombre, region) values (167, 'Rosaceae', 'Huangban');
insert into clase (codigo, nombre, region) values (168, 'Campanulaceae', 'Sabana Iglesia');
insert into clase (codigo, nombre, region) values (169, 'Cyperaceae', 'Taoyuan');
insert into clase (codigo, nombre, region) values (170, 'Selaginellaceae', 'Caihua');
insert into clase (codigo, nombre, region) values (171, 'Cyperaceae', 'Colquemarca');
insert into clase (codigo, nombre, region) values (172, 'Cyperaceae', 'Chaem Luang');
insert into clase (codigo, nombre, region) values (173, 'Rosaceae', 'Dinan');
insert into clase (codigo, nombre, region) values (174, 'Fabaceae', 'Dahuaishu');
insert into clase (codigo, nombre, region) values (175, 'Liliaceae', 'Lindavista');
insert into clase (codigo, nombre, region) values (176, 'Poaceae', 'São Lourenço da Mata');
insert into clase (codigo, nombre, region) values (177, 'Piperaceae', 'Suicheng');
insert into clase (codigo, nombre, region) values (178, 'Anemiaceae', 'Hvar');
insert into clase (codigo, nombre, region) values (179, 'Fabaceae', 'Uppsala');
insert into clase (codigo, nombre, region) values (180, 'Celastraceae', 'Avignon');
insert into clase (codigo, nombre, region) values (181, 'Collemataceae', 'Heshui');
insert into clase (codigo, nombre, region) values (182, 'Asteraceae', 'Bayan');
insert into clase (codigo, nombre, region) values (183, 'Onagraceae', 'Marcos Juárez');
insert into clase (codigo, nombre, region) values (184, 'Campanulaceae', 'Pueblo Nuevo');
insert into clase (codigo, nombre, region) values (185, 'Celastraceae', 'Severodvinsk');
insert into clase (codigo, nombre, region) values (186, 'Rhamnaceae', 'Saint-Julien-en-Genevois');
insert into clase (codigo, nombre, region) values (187, 'Physciaceae', 'Ābyek');
insert into clase (codigo, nombre, region) values (188, 'Asteraceae', 'Axioúpoli');
insert into clase (codigo, nombre, region) values (189, 'Caryophyllaceae', 'Chão');
insert into clase (codigo, nombre, region) values (190, 'Caryophyllaceae', 'Nurlat');
insert into clase (codigo, nombre, region) values (191, 'Polygonaceae', 'Tekikbanyuurip');
insert into clase (codigo, nombre, region) values (192, 'Scrophulariaceae', 'Çepan');
insert into clase (codigo, nombre, region) values (193, 'Verrucariaceae', '‘Alī al Gharbī');
insert into clase (codigo, nombre, region) values (194, 'Uncertain Ascomycota Family', 'Sulahan');
insert into clase (codigo, nombre, region) values (195, 'Scrophulariaceae', 'Bāfq');
insert into clase (codigo, nombre, region) values (196, 'Dicranaceae', 'Naukot');
insert into clase (codigo, nombre, region) values (197, 'Hydrophyllaceae', 'Jieshipu');
insert into clase (codigo, nombre, region) values (198, 'Asteraceae', 'North Cowichan');
insert into clase (codigo, nombre, region) values (199, 'Cyperaceae', 'El Coco');
insert into clase (codigo, nombre, region) values (200, 'Chenopodiaceae', 'Jiangxi');
insert into clase (codigo, nombre, region) values (201, 'Cyperaceae', 'Yong’an');
insert into clase (codigo, nombre, region) values (202, 'Pertusariaceae', 'Huacao');
insert into clase (codigo, nombre, region) values (203, 'Polygonaceae', 'Dashuipo');
insert into clase (codigo, nombre, region) values (204, 'Asteraceae', 'Shanhou');
insert into clase (codigo, nombre, region) values (205, 'Scrophulariaceae', 'Budenovetc');
insert into clase (codigo, nombre, region) values (206, 'Fabaceae', 'Esmoriz');
insert into clase (codigo, nombre, region) values (207, 'Verrucariaceae', 'New Orleans');
insert into clase (codigo, nombre, region) values (208, 'Acanthaceae', 'Khuma');
insert into clase (codigo, nombre, region) values (209, 'Ranunculaceae', 'Nadvoitsy');
insert into clase (codigo, nombre, region) values (210, 'Platanaceae', 'Gotemba');
insert into clase (codigo, nombre, region) values (211, 'Liliaceae', 'Katsuyama');
insert into clase (codigo, nombre, region) values (212, 'Ranunculaceae', 'Aţ Ţawāḩīn');
insert into clase (codigo, nombre, region) values (213, 'Asteraceae', 'Oullins');
insert into clase (codigo, nombre, region) values (214, 'Lauraceae', 'Wuying');
insert into clase (codigo, nombre, region) values (215, 'Polemoniaceae', 'Idah');
insert into clase (codigo, nombre, region) values (216, 'Pottiaceae', 'Pulo');
insert into clase (codigo, nombre, region) values (217, 'Scrophulariaceae', 'El Hamma');
insert into clase (codigo, nombre, region) values (218, 'Sparganiaceae', 'Wilanagara');
insert into clase (codigo, nombre, region) values (219, 'Asteraceae', 'Pinhal Novo');
insert into clase (codigo, nombre, region) values (220, 'Liliaceae', 'Nunsena');
insert into clase (codigo, nombre, region) values (221, 'Apiaceae', 'Sala');
insert into clase (codigo, nombre, region) values (222, 'Onagraceae', 'Maredakamau');
insert into clase (codigo, nombre, region) values (223, 'Acanthaceae', 'Pendembu');
insert into clase (codigo, nombre, region) values (224, 'Poaceae', 'Jiaoshi');
insert into clase (codigo, nombre, region) values (225, 'Solanaceae', 'Huai’an');
insert into clase (codigo, nombre, region) values (226, 'Verbenaceae', 'Novoselec');
insert into clase (codigo, nombre, region) values (227, 'Gesneriaceae', 'Kachkanar');
insert into clase (codigo, nombre, region) values (228, 'Asclepiadaceae', 'Wengang');
insert into clase (codigo, nombre, region) values (229, 'Fabaceae', 'Aitape');
insert into clase (codigo, nombre, region) values (230, 'Fabaceae', 'Nice');
insert into clase (codigo, nombre, region) values (231, 'Rosaceae', 'Stockholm');
insert into clase (codigo, nombre, region) values (232, 'Asteraceae', 'Socorro');
insert into clase (codigo, nombre, region) values (233, 'Lecanoraceae', 'Lajeado');
insert into clase (codigo, nombre, region) values (234, 'Polygalaceae', 'Hezuo');
insert into clase (codigo, nombre, region) values (235, 'Asteraceae', 'Andradina');
insert into clase (codigo, nombre, region) values (236, 'Meesiaceae', 'Kushnytsya');
insert into clase (codigo, nombre, region) values (237, 'Cyperaceae', 'Pulaupinang');
insert into clase (codigo, nombre, region) values (238, 'Rubiaceae', 'Nelipyno');
insert into clase (codigo, nombre, region) values (239, 'Orthotrichaceae', 'Jinquan');
insert into clase (codigo, nombre, region) values (240, 'Teloschistaceae', 'Bogoria');
insert into clase (codigo, nombre, region) values (241, 'Hypnaceae', 'Margahayu');
insert into clase (codigo, nombre, region) values (242, 'Cyrillaceae', 'Kasukabe');
insert into clase (codigo, nombre, region) values (243, 'Acarosporaceae', 'Bosaso');
insert into clase (codigo, nombre, region) values (244, 'Magnoliaceae', 'Srpska Crnja');
insert into clase (codigo, nombre, region) values (245, 'Rubiaceae', 'Barão de Cocais');
insert into clase (codigo, nombre, region) values (246, 'Thamnobryaceae', 'Hartford');
insert into clase (codigo, nombre, region) values (247, 'Asteraceae', 'Senta');
insert into clase (codigo, nombre, region) values (248, 'Asteraceae', 'San Antonio');
insert into clase (codigo, nombre, region) values (249, 'Uncertain Ascomycota Family', 'Qinshan');
insert into clase (codigo, nombre, region) values (250, 'Thymelaeaceae', 'Cikai');
insert into clase (codigo, nombre, region) values (251, 'Nymphaeaceae', 'Berlin');
insert into clase (codigo, nombre, region) values (252, 'Pittosporaceae', 'Tiwi');
insert into clase (codigo, nombre, region) values (253, 'Polygonaceae', 'Rosthern');
insert into clase (codigo, nombre, region) values (254, 'Asteraceae', 'Kediren');
insert into clase (codigo, nombre, region) values (255, 'Lecideaceae', 'Tsuyama');
insert into clase (codigo, nombre, region) values (256, 'Ericaceae', 'Sanqishi');
insert into clase (codigo, nombre, region) values (257, 'Cucurbitaceae', 'Su’ao');
insert into clase (codigo, nombre, region) values (258, 'Arecaceae', 'Doumen');
insert into clase (codigo, nombre, region) values (259, 'Begoniaceae', 'Cilongkrangpusaka');
insert into clase (codigo, nombre, region) values (260, 'Orchidaceae', 'Lusong');
insert into clase (codigo, nombre, region) values (261, 'Bignoniaceae', 'Telhado');
insert into clase (codigo, nombre, region) values (262, 'Boraginaceae', 'São Francisco do Sul');
insert into clase (codigo, nombre, region) values (263, 'Verrucariaceae', 'Vítkov');
insert into clase (codigo, nombre, region) values (264, 'Brassicaceae', 'Zhonghe');
insert into clase (codigo, nombre, region) values (265, 'Polygonaceae', 'El Limon');
insert into clase (codigo, nombre, region) values (266, 'Monotropaceae', 'Kachia');
insert into clase (codigo, nombre, region) values (267, 'Poaceae', 'Shaba Zhen');
insert into clase (codigo, nombre, region) values (268, 'Thymelaeaceae', 'Chitungwiza');
insert into clase (codigo, nombre, region) values (269, 'Rosaceae', 'Nanchoc');
insert into clase (codigo, nombre, region) values (270, 'Poaceae', 'Mainri');
insert into clase (codigo, nombre, region) values (271, 'Cyperaceae', 'Dauriya');
insert into clase (codigo, nombre, region) values (272, 'Menyanthaceae', 'Buçimas');
insert into clase (codigo, nombre, region) values (273, 'Pinaceae', 'Tilmi');
insert into clase (codigo, nombre, region) values (274, 'Asteraceae', 'Kotawaikabubak');
insert into clase (codigo, nombre, region) values (275, 'Polypodiaceae', 'Baabda');
insert into clase (codigo, nombre, region) values (276, 'Fabaceae', 'Žiželice');
insert into clase (codigo, nombre, region) values (277, 'Asteraceae', 'Kalengwa');
insert into clase (codigo, nombre, region) values (278, 'Rhizocarpaceae', 'Ise');
insert into clase (codigo, nombre, region) values (279, 'Fabaceae', 'Yinxi');
insert into clase (codigo, nombre, region) values (280, 'Geraniaceae', 'Paraiso');
insert into clase (codigo, nombre, region) values (281, 'Lamiaceae', 'Borlänge');
insert into clase (codigo, nombre, region) values (282, 'Poaceae', 'Changhe');
insert into clase (codigo, nombre, region) values (283, 'Asteraceae', 'Khiwa');
insert into clase (codigo, nombre, region) values (284, 'Asteraceae', 'Abreus');
insert into clase (codigo, nombre, region) values (285, 'Boraginaceae', 'Berlin');
insert into clase (codigo, nombre, region) values (286, 'Asteraceae', 'Otrado-Kubanskoye');
insert into clase (codigo, nombre, region) values (287, 'Fabaceae', 'Beitai');
insert into clase (codigo, nombre, region) values (288, 'Rosaceae', 'Zaoshi');
insert into clase (codigo, nombre, region) values (289, 'Rubiaceae', 'Nam Kliang');
insert into clase (codigo, nombre, region) values (290, 'Polygalaceae', 'Gwangju');
insert into clase (codigo, nombre, region) values (291, 'Fabaceae', 'Urbano Noris');
insert into clase (codigo, nombre, region) values (292, 'Crassulaceae', 'Tegalsari');
insert into clase (codigo, nombre, region) values (293, 'Piperaceae', 'Huangjingba');
insert into clase (codigo, nombre, region) values (294, 'Amaranthaceae', 'Sagana');
insert into clase (codigo, nombre, region) values (295, 'Pontederiaceae', 'Byerazino');
insert into clase (codigo, nombre, region) values (296, 'Apiaceae', 'Santiago de Cao');
insert into clase (codigo, nombre, region) values (297, 'Clusiaceae', 'Dajin');
insert into clase (codigo, nombre, region) values (298, 'Cladoniaceae', 'Jakubowice Murowane');
insert into clase (codigo, nombre, region) values (299, 'Capnodiaceae', 'Tanjay');
insert into clase (codigo, nombre, region) values (300, 'Thymelaeaceae', 'Katsina-Ala');
insert into clase (codigo, nombre, region) values (301, 'Dryopteridaceae', 'Menglie');
insert into clase (codigo, nombre, region) values (302, 'Ramalinaceae', 'Bassano');
insert into clase (codigo, nombre, region) values (303, 'Fabaceae', 'Liufu');
insert into clase (codigo, nombre, region) values (304, 'Brassicaceae', 'Chiscas');
insert into clase (codigo, nombre, region) values (305, 'Scrophulariaceae', 'Eišiškės');
insert into clase (codigo, nombre, region) values (306, 'Proteaceae', 'Bueng Kan');
insert into clase (codigo, nombre, region) values (307, 'Orchidaceae', 'Kertasari');
insert into clase (codigo, nombre, region) values (308, 'Fontinalaceae', 'Duut');
insert into clase (codigo, nombre, region) values (309, 'Asteraceae', 'Levashi');
insert into clase (codigo, nombre, region) values (310, 'Boraginaceae', 'Xinglong');
insert into clase (codigo, nombre, region) values (311, 'Poaceae', 'Socorro');
insert into clase (codigo, nombre, region) values (312, 'Gesneriaceae', 'Itabirito');
insert into clase (codigo, nombre, region) values (313, 'Boraginaceae', 'Dugongan');
insert into clase (codigo, nombre, region) values (314, 'Asteraceae', 'Chidian');
insert into clase (codigo, nombre, region) values (315, 'Fabaceae', 'Žabčice');
insert into clase (codigo, nombre, region) values (316, 'Poaceae', 'Předměřice nad Labem');
insert into clase (codigo, nombre, region) values (317, 'Vezdaeaceae', 'Ushirombo');
insert into clase (codigo, nombre, region) values (318, 'Sphagnaceae', 'Orleans');
insert into clase (codigo, nombre, region) values (319, 'Lamiaceae', 'Shayu');
insert into clase (codigo, nombre, region) values (320, 'Crossosomataceae', 'Lagayan');
insert into clase (codigo, nombre, region) values (321, 'Fabaceae', 'Kano');
insert into clase (codigo, nombre, region) values (322, 'Loasaceae', 'Cacocum');
insert into clase (codigo, nombre, region) values (323, 'Scrophulariaceae', 'Elat');
insert into clase (codigo, nombre, region) values (324, 'Parmeliaceae', 'Novobiryusinskiy');
insert into clase (codigo, nombre, region) values (325, 'Brassicaceae', 'Aksakovo');
insert into clase (codigo, nombre, region) values (326, 'Fabaceae', 'Kumla');
insert into clase (codigo, nombre, region) values (327, 'Asteraceae', 'Candelária');
insert into clase (codigo, nombre, region) values (328, 'Thymelaeaceae', 'Garden Grove');
insert into clase (codigo, nombre, region) values (329, 'Aceraceae', 'Yashao');
insert into clase (codigo, nombre, region) values (330, 'Cyperaceae', 'Beiyang');
insert into clase (codigo, nombre, region) values (331, 'Polemoniaceae', 'Yushu');
insert into clase (codigo, nombre, region) values (332, 'Geraniaceae', 'Jansenville');
insert into clase (codigo, nombre, region) values (333, 'Hymenophyllaceae', 'Mirões');
insert into clase (codigo, nombre, region) values (334, 'Leucodontaceae', 'Yukuhashi');
insert into clase (codigo, nombre, region) values (335, 'Myrtaceae', 'Kiuruvesi');
insert into clase (codigo, nombre, region) values (336, 'Asteraceae', 'Calimete');
insert into clase (codigo, nombre, region) values (337, 'Strigulaceae', 'Lykóvrysi');
insert into clase (codigo, nombre, region) values (338, 'Dryopteridaceae', 'Ånge');
insert into clase (codigo, nombre, region) values (339, 'Lycopodiaceae', 'Prupuh');
insert into clase (codigo, nombre, region) values (340, 'Poaceae', 'Shah Alam');
insert into clase (codigo, nombre, region) values (341, 'Asteraceae', 'Bibrka');
insert into clase (codigo, nombre, region) values (342, 'Cyperaceae', 'Moate');
insert into clase (codigo, nombre, region) values (343, 'Boraginaceae', 'Tinogasta');
insert into clase (codigo, nombre, region) values (344, 'Fagaceae', 'Watulimo');
insert into clase (codigo, nombre, region) values (345, 'Portulacaceae', 'Libertador General San Martín');
insert into clase (codigo, nombre, region) values (346, 'Scrophulariaceae', 'Hoit Taria');
insert into clase (codigo, nombre, region) values (347, 'Meliaceae', 'Ōkuchi');
insert into clase (codigo, nombre, region) values (348, 'Saxifragaceae', 'Sidu');
insert into clase (codigo, nombre, region) values (349, 'Fabaceae', 'Monte');
insert into clase (codigo, nombre, region) values (350, 'Thelypteridaceae', 'Pivka');
insert into clase (codigo, nombre, region) values (351, 'Cyperaceae', 'Chełm');
insert into clase (codigo, nombre, region) values (352, 'Gentianaceae', 'Aranas Sur');
insert into clase (codigo, nombre, region) values (353, 'Oxalidaceae', 'Baláo');
insert into clase (codigo, nombre, region) values (354, 'Scrophulariaceae', 'São Pedro de Muel');
insert into clase (codigo, nombre, region) values (355, 'Malvaceae', 'Al Manzilah');
insert into clase (codigo, nombre, region) values (356, 'Pottiaceae', 'Jianfeng');
insert into clase (codigo, nombre, region) values (357, 'Euphorbiaceae', 'Chongru');
insert into clase (codigo, nombre, region) values (358, 'Boraginaceae', 'Ketangi');
insert into clase (codigo, nombre, region) values (359, 'Lemnaceae', 'Sosnytsya');
insert into clase (codigo, nombre, region) values (360, 'Poaceae', 'Langkap');
insert into clase (codigo, nombre, region) values (361, 'Fabaceae', 'Dayr Mawās');
insert into clase (codigo, nombre, region) values (362, 'Rosaceae', 'La Palma');
insert into clase (codigo, nombre, region) values (363, 'Rubiaceae', 'Chironkamba');
insert into clase (codigo, nombre, region) values (364, 'Gentianaceae', 'Shufeng');
insert into clase (codigo, nombre, region) values (365, 'Pinaceae', 'Jin’an');
insert into clase (codigo, nombre, region) values (366, 'Heliconiaceae', 'Almaznyy');
insert into clase (codigo, nombre, region) values (367, 'Brassicaceae', 'Capulaan');
insert into clase (codigo, nombre, region) values (368, 'Asteraceae', 'Governador Valadares');
insert into clase (codigo, nombre, region) values (369, 'Brassicaceae', 'Wonorejo');
insert into clase (codigo, nombre, region) values (370, 'Scrophulariaceae', 'Santana do Ipanema');
insert into clase (codigo, nombre, region) values (371, 'Asclepiadaceae', 'Longcheng');
insert into clase (codigo, nombre, region) values (372, 'Primulaceae', 'Belo Horizonte');
insert into clase (codigo, nombre, region) values (373, 'Violaceae', 'Dzhetygara');
insert into clase (codigo, nombre, region) values (374, 'Brassicaceae', 'Shiree');
insert into clase (codigo, nombre, region) values (375, 'Campanulaceae', 'Dajanrurung');
insert into clase (codigo, nombre, region) values (376, 'Orchidaceae', 'Krasica');
insert into clase (codigo, nombre, region) values (377, 'Scrophulariaceae', 'Tall aḑ Ḑamān');
insert into clase (codigo, nombre, region) values (378, 'Fabaceae', 'Hafrsfjord');
insert into clase (codigo, nombre, region) values (379, 'Polemoniaceae', 'Kunów');
insert into clase (codigo, nombre, region) values (380, 'Fabaceae', 'Qiankeng');
insert into clase (codigo, nombre, region) values (381, 'Pertusariaceae', 'Shedok');
insert into clase (codigo, nombre, region) values (382, 'Rosaceae', 'Solnechnyy');
insert into clase (codigo, nombre, region) values (383, 'Fabaceae', 'Oslo');
insert into clase (codigo, nombre, region) values (384, 'Polygonaceae', 'Lyubimets');
insert into clase (codigo, nombre, region) values (385, 'Rosaceae', 'Klagen');
insert into clase (codigo, nombre, region) values (386, 'Onagraceae', 'Caigongzhuang');
insert into clase (codigo, nombre, region) values (387, 'Cuscutaceae', 'Xiaoguwei');
insert into clase (codigo, nombre, region) values (388, 'Sapotaceae', 'Dobrich');
insert into clase (codigo, nombre, region) values (389, 'Asteraceae', 'Sinazongwe');
insert into clase (codigo, nombre, region) values (390, 'Lamiaceae', 'Guarenas');
insert into clase (codigo, nombre, region) values (391, 'Nyctaginaceae', 'Jiantiao');
insert into clase (codigo, nombre, region) values (392, 'Asteraceae', 'Sosándra');
insert into clase (codigo, nombre, region) values (393, 'Asteraceae', 'Gornje Moštre');
insert into clase (codigo, nombre, region) values (394, 'Juglandaceae', 'Ventspils');
insert into clase (codigo, nombre, region) values (395, 'Euphorbiaceae', 'Itaocara');
insert into clase (codigo, nombre, region) values (396, 'Ranunculaceae', 'Nanae');
insert into clase (codigo, nombre, region) values (397, 'Saxifragaceae', 'Ryczywół');
insert into clase (codigo, nombre, region) values (398, 'Apiaceae', 'Thị Trấn Ngan Dừa');
insert into clase (codigo, nombre, region) values (399, 'Asteraceae', 'Zolotyy Potik');
insert into clase (codigo, nombre, region) values (400, 'Fabaceae', 'Guandu');
insert into clase (codigo, nombre, region) values (401, 'Asclepiadaceae', 'Tetaf');
insert into clase (codigo, nombre, region) values (402, 'Ptychomitriaceae', 'San José de Jáchal');
insert into clase (codigo, nombre, region) values (403, 'Fagaceae', 'Kedungwaru');
insert into clase (codigo, nombre, region) values (404, 'Boraginaceae', 'Wuquan');
insert into clase (codigo, nombre, region) values (405, 'Loasaceae', 'Yueyang');
insert into clase (codigo, nombre, region) values (406, 'Solanaceae', 'Gukovo');
insert into clase (codigo, nombre, region) values (407, 'Cannaceae', 'Zhoukou');
insert into clase (codigo, nombre, region) values (408, 'Hydrangeaceae', 'Junqueiro');
insert into clase (codigo, nombre, region) values (409, 'Hydrocharitaceae', 'Ñuñoa');
insert into clase (codigo, nombre, region) values (410, 'Euphorbiaceae', 'Tadianjie');
insert into clase (codigo, nombre, region) values (411, 'Malvaceae', 'Ipís');
insert into clase (codigo, nombre, region) values (412, 'Cyperaceae', 'Vyshniy Volochëk');
insert into clase (codigo, nombre, region) values (413, 'Poaceae', 'Kolbuszowa');
insert into clase (codigo, nombre, region) values (414, 'Convolvulaceae', 'Itaperuna');
insert into clase (codigo, nombre, region) values (415, 'Rosaceae', 'El Bolsón');
insert into clase (codigo, nombre, region) values (416, 'Hydrophyllaceae', 'Leganes');
insert into clase (codigo, nombre, region) values (417, 'Stictidaceae', 'Tanggul Wetan');
insert into clase (codigo, nombre, region) values (418, 'Rosaceae', 'Belköl');
insert into clase (codigo, nombre, region) values (419, 'Annonaceae', 'Ilyich');
insert into clase (codigo, nombre, region) values (420, 'Hypnaceae', 'San Casimiro');
insert into clase (codigo, nombre, region) values (421, 'Polygonaceae', 'Siedliska');
insert into clase (codigo, nombre, region) values (422, 'Dryopteridaceae', 'Guarda Nova');
insert into clase (codigo, nombre, region) values (423, 'Hymenophyllaceae', 'Lanyang');
insert into clase (codigo, nombre, region) values (424, 'Marsileaceae', 'Radashkovichy');
insert into clase (codigo, nombre, region) values (425, 'Lamiaceae', 'Santa Ana');
insert into clase (codigo, nombre, region) values (426, 'Thelypteridaceae', 'Koga');
insert into clase (codigo, nombre, region) values (427, 'Poaceae', 'Mengxingzhuang');
insert into clase (codigo, nombre, region) values (428, 'Fabaceae', 'Jaunpiebalga');
insert into clase (codigo, nombre, region) values (429, 'Solanaceae', 'Kista');
insert into clase (codigo, nombre, region) values (430, 'Poaceae', 'Błędów');
insert into clase (codigo, nombre, region) values (431, 'Plantaginaceae', 'Yogyakarta');
insert into clase (codigo, nombre, region) values (432, 'Fabaceae', 'Shi’ao');
insert into clase (codigo, nombre, region) values (433, 'Nyctaginaceae', 'Noşratābād');
insert into clase (codigo, nombre, region) values (434, 'Myrtaceae', 'Lorica');
insert into clase (codigo, nombre, region) values (435, 'Polygonaceae', 'Cigebrok');
insert into clase (codigo, nombre, region) values (436, 'Seligeriaceae', 'Vänersborg');
insert into clase (codigo, nombre, region) values (437, 'Fabaceae', 'Ciego de Ávila');
insert into clase (codigo, nombre, region) values (438, 'Cornaceae', 'Iberia');
insert into clase (codigo, nombre, region) values (439, 'Lecanoraceae', 'Orodo');
insert into clase (codigo, nombre, region) values (440, 'Fabaceae', 'Revava');
insert into clase (codigo, nombre, region) values (441, 'Rosaceae', 'Mislīyah');
insert into clase (codigo, nombre, region) values (442, 'Malvaceae', 'Laixi');
insert into clase (codigo, nombre, region) values (443, 'Cyperaceae', 'Konza');
insert into clase (codigo, nombre, region) values (444, 'Acanthaceae', 'Iwanuma');
insert into clase (codigo, nombre, region) values (445, 'Graphidaceae', 'Jose Maria Morelos');
insert into clase (codigo, nombre, region) values (446, 'Cucurbitaceae', 'Santa Maria');
insert into clase (codigo, nombre, region) values (447, 'Ruppiaceae', 'Manturovo');
insert into clase (codigo, nombre, region) values (448, 'Convolvulaceae', 'Mengla');
insert into clase (codigo, nombre, region) values (449, 'Apocynaceae', 'Iporã');
insert into clase (codigo, nombre, region) values (450, 'Poaceae', 'Littleton');
insert into clase (codigo, nombre, region) values (451, 'Linaceae', 'Uruaçu');
insert into clase (codigo, nombre, region) values (452, 'Onagraceae', 'Ulyanovsk');
insert into clase (codigo, nombre, region) values (453, 'Fabaceae', 'Condega');
insert into clase (codigo, nombre, region) values (454, 'Ericaceae', 'Melekyne');
insert into clase (codigo, nombre, region) values (455, 'Asteraceae', 'Tumba');
insert into clase (codigo, nombre, region) values (456, 'Asteraceae', 'Omaruru');
insert into clase (codigo, nombre, region) values (457, 'Onagraceae', 'Mislak');
insert into clase (codigo, nombre, region) values (458, 'Betulaceae', 'Rungis');
insert into clase (codigo, nombre, region) values (459, 'Rubiaceae', 'Alta');
insert into clase (codigo, nombre, region) values (460, 'Asteraceae', 'Tipaz');
insert into clase (codigo, nombre, region) values (461, 'Polemoniaceae', 'Kitchener');
insert into clase (codigo, nombre, region) values (462, 'Poaceae', 'Guling');
insert into clase (codigo, nombre, region) values (463, 'Gentianaceae', 'Savitaipale');
insert into clase (codigo, nombre, region) values (464, 'Parmeliaceae', 'Nicoya');
insert into clase (codigo, nombre, region) values (465, 'Ericaceae', 'Saint-Denis');
insert into clase (codigo, nombre, region) values (466, 'Poaceae', 'Sepīdān');
insert into clase (codigo, nombre, region) values (467, 'Lamiaceae', 'Heshan');
insert into clase (codigo, nombre, region) values (468, 'Convolvulaceae', 'Saint John');
insert into clase (codigo, nombre, region) values (469, 'Scrophulariaceae', 'Bayan Qagan');
insert into clase (codigo, nombre, region) values (470, 'Brassicaceae', 'Adir');
insert into clase (codigo, nombre, region) values (471, 'Asteraceae', 'Jiaotang');
insert into clase (codigo, nombre, region) values (472, 'Malpighiaceae', 'Dologon');
insert into clase (codigo, nombre, region) values (473, 'Hypnaceae', 'Aengceleng');
insert into clase (codigo, nombre, region) values (474, 'Asteraceae', 'Las Junturas');
insert into clase (codigo, nombre, region) values (475, 'Orchidaceae', 'Darunban');
insert into clase (codigo, nombre, region) values (476, 'Convolvulaceae', 'Kuala Bhee');
insert into clase (codigo, nombre, region) values (477, 'Rosaceae', 'Bweyogerere');
insert into clase (codigo, nombre, region) values (478, 'Oleaceae', 'Opatów');
insert into clase (codigo, nombre, region) values (479, 'Fagaceae', 'Talcahuano');
insert into clase (codigo, nombre, region) values (480, 'Polygonaceae', 'Novo-Peredelkino');
insert into clase (codigo, nombre, region) values (481, 'Onagraceae', 'Mina de São Domingos');
insert into clase (codigo, nombre, region) values (482, 'Lichinaceae', 'Businga');
insert into clase (codigo, nombre, region) values (483, 'Campanulaceae', 'Jiekeng');
insert into clase (codigo, nombre, region) values (484, 'Poaceae', 'Langtad');
insert into clase (codigo, nombre, region) values (485, 'Aizoaceae', 'Van Nuys');
insert into clase (codigo, nombre, region) values (486, 'Cucurbitaceae', 'Niafunké');
insert into clase (codigo, nombre, region) values (487, 'Asteraceae', 'Maroantsetra');
insert into clase (codigo, nombre, region) values (488, 'Brachytheciaceae', 'Huayana');
insert into clase (codigo, nombre, region) values (489, 'Portulacaceae', 'Banjar Kawan');
insert into clase (codigo, nombre, region) values (490, 'Viscaceae', 'Paris 02');
insert into clase (codigo, nombre, region) values (491, 'Fabaceae', 'La Guacamaya');
insert into clase (codigo, nombre, region) values (492, 'Verrucariaceae', 'Amsterdam-Oost');
insert into clase (codigo, nombre, region) values (493, 'Cyperaceae', 'Nanyi');
insert into clase (codigo, nombre, region) values (494, 'Fabaceae', 'Milton');
insert into clase (codigo, nombre, region) values (495, 'Rhamnaceae', 'Pinggang');
insert into clase (codigo, nombre, region) values (496, 'Myricaceae', 'Nuamuzi');
insert into clase (codigo, nombre, region) values (497, 'Grossulariaceae', 'Las Vegas');
insert into clase (codigo, nombre, region) values (498, 'Liliaceae', 'Gamboula');
insert into clase (codigo, nombre, region) values (499, 'Stictidaceae', 'Östersund');
insert into clase (codigo, nombre, region) values (500, 'Lamiaceae', 'Portorož');
insert into clase (codigo, nombre, region) values (501, 'Asteraceae', 'Nikolo-Pavlovskoye');
insert into clase (codigo, nombre, region) values (502, 'Begoniaceae', 'Monte da Chaminé');
insert into clase (codigo, nombre, region) values (503, 'Geraniaceae', 'Longshan');
insert into clase (codigo, nombre, region) values (504, 'Primulaceae', 'Camplong');
insert into clase (codigo, nombre, region) values (505, 'Lecideaceae', 'Jungutbatu Kaja Dua');
insert into clase (codigo, nombre, region) values (506, 'Caryophyllaceae', 'Dimitrovgrad');
insert into clase (codigo, nombre, region) values (507, 'Marantaceae', 'Trai Ngau');
insert into clase (codigo, nombre, region) values (508, 'Poaceae', 'Ayang-ni');
insert into clase (codigo, nombre, region) values (509, 'Brassicaceae', 'Panyambungan');
insert into clase (codigo, nombre, region) values (510, 'Malvaceae', 'Rāmganj');
insert into clase (codigo, nombre, region) values (511, 'Cyperaceae', 'Sudogda');
insert into clase (codigo, nombre, region) values (512, 'Acarosporaceae', 'Huze');
insert into clase (codigo, nombre, region) values (513, 'Cyperaceae', 'Nyala');
insert into clase (codigo, nombre, region) values (514, 'Polygonaceae', 'Mabini');
insert into clase (codigo, nombre, region) values (515, 'Campanulaceae', 'Guacara');
insert into clase (codigo, nombre, region) values (516, 'Primulaceae', 'Pampas Chico');
insert into clase (codigo, nombre, region) values (517, 'Poaceae', 'Xianzong');
insert into clase (codigo, nombre, region) values (518, 'Poaceae', 'Indaiatuba');
insert into clase (codigo, nombre, region) values (519, 'Scrophulariaceae', 'Hŭngnam');
insert into clase (codigo, nombre, region) values (520, 'Lecanoraceae', 'Kalvola');
insert into clase (codigo, nombre, region) values (521, 'Cactaceae', 'Lengshuijing');
insert into clase (codigo, nombre, region) values (522, 'Primulaceae', 'Oliveira de Baixo');
insert into clase (codigo, nombre, region) values (523, 'Apiaceae', 'Suban Jeriji');
insert into clase (codigo, nombre, region) values (524, 'Asteraceae', 'San Antonio');
insert into clase (codigo, nombre, region) values (525, 'Poaceae', 'Sumbawa Besar');
insert into clase (codigo, nombre, region) values (526, 'Lecanoraceae', 'Zhangqing');
insert into clase (codigo, nombre, region) values (527, 'Euphorbiaceae', 'Dongshan');
insert into clase (codigo, nombre, region) values (528, 'Crassulaceae', 'Semeljci');
insert into clase (codigo, nombre, region) values (529, 'Parmeliaceae', 'Montesson');
insert into clase (codigo, nombre, region) values (530, 'Asteraceae', 'Tournon-sur-Rhône');
insert into clase (codigo, nombre, region) values (531, 'Poaceae', 'Jamālpur');
insert into clase (codigo, nombre, region) values (532, 'Cladoniaceae', 'Älmhult');
insert into clase (codigo, nombre, region) values (533, 'Lamiaceae', 'Havirga');
insert into clase (codigo, nombre, region) values (534, 'Urticaceae', 'Klenica');
insert into clase (codigo, nombre, region) values (535, 'Fabaceae', 'Itami');
insert into clase (codigo, nombre, region) values (536, 'Fabaceae', 'Vologda');
insert into clase (codigo, nombre, region) values (537, 'Viscaceae', 'Blon’');
insert into clase (codigo, nombre, region) values (538, 'Pteridaceae', 'Outing');
insert into clase (codigo, nombre, region) values (539, 'Dryopteridaceae', 'Sayang Lauq');
insert into clase (codigo, nombre, region) values (540, 'Lythraceae', 'Kota Kinabalu');
insert into clase (codigo, nombre, region) values (541, 'Fabaceae', 'Gorna Oryakhovitsa');
insert into clase (codigo, nombre, region) values (542, 'Poaceae', 'Eskilstuna');
insert into clase (codigo, nombre, region) values (543, 'Orchidaceae', 'Sukhobuzimskoye');
insert into clase (codigo, nombre, region) values (544, 'Fabaceae', 'Haligue');
insert into clase (codigo, nombre, region) values (545, 'Polytrichaceae', 'Cilongkrangpusaka');
insert into clase (codigo, nombre, region) values (546, 'Arecaceae', 'Jatiwangi');
insert into clase (codigo, nombre, region) values (547, 'Scrophulariaceae', 'Ayotupas');
insert into clase (codigo, nombre, region) values (548, 'Zingiberaceae', 'Asahikawa');
insert into clase (codigo, nombre, region) values (549, 'Polemoniaceae', 'Ōsaka-shi');
insert into clase (codigo, nombre, region) values (550, 'Fabaceae', 'Talashkino');
insert into clase (codigo, nombre, region) values (551, 'Fagaceae', 'Mattaldi');
insert into clase (codigo, nombre, region) values (552, 'Ericaceae', 'Frýdlant');
insert into clase (codigo, nombre, region) values (553, 'Cyperaceae', 'Rennes');
insert into clase (codigo, nombre, region) values (554, 'Fabaceae', 'Pā’īn-e Bāzār-e Rūdbār');
insert into clase (codigo, nombre, region) values (555, 'Clusiaceae', 'Dongfanghong');
insert into clase (codigo, nombre, region) values (556, 'Polemoniaceae', 'Santa Cruz de la Sierra');
insert into clase (codigo, nombre, region) values (557, 'Cyperaceae', 'Albacete');
insert into clase (codigo, nombre, region) values (558, 'Cyperaceae', 'Pomerode');
insert into clase (codigo, nombre, region) values (559, 'Fabaceae', 'Pokrovskoye-Streshnëvo');
insert into clase (codigo, nombre, region) values (560, 'Cyperaceae', 'Sarāvān');
insert into clase (codigo, nombre, region) values (561, 'Fabaceae', 'Slovenski Javornik');
insert into clase (codigo, nombre, region) values (562, 'Rosaceae', 'Bonneuil-sur-Marne');
insert into clase (codigo, nombre, region) values (563, 'Brassicaceae', 'Huayacundo Arma');
insert into clase (codigo, nombre, region) values (564, 'Poaceae', 'Jinhe');
insert into clase (codigo, nombre, region) values (565, 'Ranunculaceae', 'Svetlograd');
insert into clase (codigo, nombre, region) values (566, 'Aizoaceae', 'Xiangyang');
insert into clase (codigo, nombre, region) values (567, 'Cucurbitaceae', 'Tyumen');
insert into clase (codigo, nombre, region) values (568, 'Asteraceae', 'Dubno');
insert into clase (codigo, nombre, region) values (569, 'Fabaceae', 'Guifeng');
insert into clase (codigo, nombre, region) values (570, 'Polygalaceae', 'Bang Mun Nak');
insert into clase (codigo, nombre, region) values (571, 'Poaceae', 'Luyang');
insert into clase (codigo, nombre, region) values (572, 'Amaranthaceae', 'Sịa');
insert into clase (codigo, nombre, region) values (573, 'Ranunculaceae', 'Akoupé');
insert into clase (codigo, nombre, region) values (574, 'Asteraceae', 'Cernay');
insert into clase (codigo, nombre, region) values (575, 'Brassicaceae', 'Haoyi');
insert into clase (codigo, nombre, region) values (576, 'Cistaceae', 'Ujsoły');
insert into clase (codigo, nombre, region) values (577, 'Rosaceae', 'Chavães');
insert into clase (codigo, nombre, region) values (578, 'Rosaceae', 'Tamarindo');
insert into clase (codigo, nombre, region) values (579, 'Gleicheniaceae', 'Souto');
insert into clase (codigo, nombre, region) values (580, 'Cactaceae', 'Barra de São Francisco');
insert into clase (codigo, nombre, region) values (581, 'Lecanoraceae', 'Laweueng');
insert into clase (codigo, nombre, region) values (582, 'Verbenaceae', 'Sacanta');
insert into clase (codigo, nombre, region) values (583, 'Rosaceae', 'Brea Pozo');
insert into clase (codigo, nombre, region) values (584, 'Asteraceae', 'Sukojember');
insert into clase (codigo, nombre, region) values (585, 'Aristolochiaceae', 'Besançon');
insert into clase (codigo, nombre, region) values (586, 'Lamiaceae', 'Urengoy');
insert into clase (codigo, nombre, region) values (587, 'Asteraceae', 'Larvik');
insert into clase (codigo, nombre, region) values (588, 'Liliaceae', 'Rumbek');
insert into clase (codigo, nombre, region) values (589, 'Fabaceae', 'Mahaddayweyne');
insert into clase (codigo, nombre, region) values (590, 'Fabaceae', 'Sun Kunda');
insert into clase (codigo, nombre, region) values (591, 'Arecaceae', 'Kramfors');
insert into clase (codigo, nombre, region) values (592, 'Rosaceae', 'Al Jamīmah');
insert into clase (codigo, nombre, region) values (593, 'Polemoniaceae', 'Ţammūn');
insert into clase (codigo, nombre, region) values (594, 'Scrophulariaceae', 'Šumice');
insert into clase (codigo, nombre, region) values (595, 'Poaceae', 'Arboga');
insert into clase (codigo, nombre, region) values (596, 'Apiaceae', 'Toulouse');
insert into clase (codigo, nombre, region) values (597, 'Fabaceae', 'Néa Kíos');
insert into clase (codigo, nombre, region) values (598, 'Saxifragaceae', 'Quezalguaque');
insert into clase (codigo, nombre, region) values (599, 'Brassicaceae', 'Magtaking');
insert into clase (codigo, nombre, region) values (600, 'Asteraceae', 'Zangzhai');
insert into clase (codigo, nombre, region) values (601, 'Cyperaceae', 'Lagoa do Itaenga');
insert into clase (codigo, nombre, region) values (602, 'Fabaceae', 'Seredyna-Buda');
insert into clase (codigo, nombre, region) values (603, 'Parmeliaceae', 'Banjarjo');
insert into clase (codigo, nombre, region) values (604, 'Orchidaceae', 'Manta');
insert into clase (codigo, nombre, region) values (605, 'Gentianaceae', 'Raşad');
insert into clase (codigo, nombre, region) values (606, 'Asteraceae', 'Azilal');
insert into clase (codigo, nombre, region) values (607, 'Orchidaceae', 'Bošovice');
insert into clase (codigo, nombre, region) values (608, 'Physciaceae', 'Palmira');
insert into clase (codigo, nombre, region) values (609, 'Brassicaceae', 'Hampang');
insert into clase (codigo, nombre, region) values (610, 'Cyperaceae', 'Moorreesburg');
insert into clase (codigo, nombre, region) values (611, 'Rutaceae', 'Harjamukti');
insert into clase (codigo, nombre, region) values (612, 'Ranunculaceae', 'Shuihu');
insert into clase (codigo, nombre, region) values (613, 'Cyperaceae', 'Choco');
insert into clase (codigo, nombre, region) values (614, 'Convolvulaceae', 'Caratinga');
insert into clase (codigo, nombre, region) values (615, 'Brassicaceae', 'Lāliān');
insert into clase (codigo, nombre, region) values (616, 'Fabaceae', 'Panitan');
insert into clase (codigo, nombre, region) values (617, 'Grimmiaceae', 'Liangbing');
insert into clase (codigo, nombre, region) values (618, 'Malvaceae', 'Gardēz');
insert into clase (codigo, nombre, region) values (619, 'Ranunculaceae', 'Gongchang Zhen');
insert into clase (codigo, nombre, region) values (620, 'Poaceae', 'Tchoban Bey');
insert into clase (codigo, nombre, region) values (621, 'Brassicaceae', 'Ciomas');
insert into clase (codigo, nombre, region) values (622, 'Rutaceae', 'Anadia');
insert into clase (codigo, nombre, region) values (623, 'Pottiaceae', 'Teongtoda');
insert into clase (codigo, nombre, region) values (624, 'Solanaceae', 'Brive-la-Gaillarde');
insert into clase (codigo, nombre, region) values (625, 'Ranunculaceae', 'La Aurora');
insert into clase (codigo, nombre, region) values (626, 'Taxaceae', 'Dasol');
insert into clase (codigo, nombre, region) values (627, 'Fabaceae', 'Honglong');
insert into clase (codigo, nombre, region) values (628, 'Liliaceae', 'Cunha');
insert into clase (codigo, nombre, region) values (629, 'Grammitidaceae', 'Rezh');
insert into clase (codigo, nombre, region) values (630, 'Commelinaceae', 'Köping');
insert into clase (codigo, nombre, region) values (631, 'Fabroniaceae', 'Saint-Flour');
insert into clase (codigo, nombre, region) values (632, 'Asteraceae', 'To’rtko’l Shahri');
insert into clase (codigo, nombre, region) values (633, 'Lamiaceae', 'Zhujiang');
insert into clase (codigo, nombre, region) values (634, 'Fabaceae', 'Rostock');
insert into clase (codigo, nombre, region) values (635, 'Pinaceae', 'Arroyo Salado');
insert into clase (codigo, nombre, region) values (636, 'Caryophyllaceae', 'Volkhov');
insert into clase (codigo, nombre, region) values (637, 'Campanulaceae', 'Novi Bečej');
insert into clase (codigo, nombre, region) values (638, 'Onagraceae', 'Kumo');
insert into clase (codigo, nombre, region) values (639, 'Pittosporaceae', 'Chai Nat');
insert into clase (codigo, nombre, region) values (640, 'Asteraceae', 'Pidvynohradiv');
insert into clase (codigo, nombre, region) values (641, 'Liliaceae', 'Riofrío');
insert into clase (codigo, nombre, region) values (642, 'Lamiaceae', 'Qingxi');
insert into clase (codigo, nombre, region) values (643, 'Euphorbiaceae', 'Taytayan');
insert into clase (codigo, nombre, region) values (644, 'Alismataceae', 'Thepharak');
insert into clase (codigo, nombre, region) values (645, 'Polypodiaceae', 'Kuznetsovs’k');
insert into clase (codigo, nombre, region) values (646, 'Portulacaceae', 'Port Erin');
insert into clase (codigo, nombre, region) values (647, 'Brassicaceae', 'Krzyżanów');
insert into clase (codigo, nombre, region) values (648, 'Lecanoraceae', 'Tampocon');
insert into clase (codigo, nombre, region) values (649, 'Vitaceae', 'Ouésso');
insert into clase (codigo, nombre, region) values (650, 'Grimmiaceae', 'Kivertsi');
insert into clase (codigo, nombre, region) values (651, 'Cyperaceae', 'Sukakerta');
insert into clase (codigo, nombre, region) values (652, 'Cactaceae', 'General Emilio Aguinaldo');
insert into clase (codigo, nombre, region) values (653, 'Passifloraceae', 'Torino');
insert into clase (codigo, nombre, region) values (654, 'Asteraceae', 'São Gabriel da Cachoeira');
insert into clase (codigo, nombre, region) values (655, 'Euphorbiaceae', 'Sujitan');
insert into clase (codigo, nombre, region) values (656, 'Rhamnaceae', 'Ringinagung');
insert into clase (codigo, nombre, region) values (657, 'Dryopteridaceae', 'Jiangkou');
insert into clase (codigo, nombre, region) values (658, 'Opegraphaceae', 'Mata');
insert into clase (codigo, nombre, region) values (659, 'Xyridaceae', 'Cluny');
insert into clase (codigo, nombre, region) values (660, 'Cyperaceae', 'Incheon');
insert into clase (codigo, nombre, region) values (661, 'Grammitidaceae', 'Huaguo');
insert into clase (codigo, nombre, region) values (662, 'Liliaceae', 'Muraloka');
insert into clase (codigo, nombre, region) values (663, 'Rhamnaceae', 'Lady Frere');
insert into clase (codigo, nombre, region) values (664, 'Fabaceae', 'San Mariano');
insert into clase (codigo, nombre, region) values (665, 'Fabaceae', 'Xinkai');
insert into clase (codigo, nombre, region) values (666, 'Brassicaceae', 'Żabno');
insert into clase (codigo, nombre, region) values (667, 'Cyperaceae', 'Noenoni');
insert into clase (codigo, nombre, region) values (668, 'Asteraceae', 'Monastir');
insert into clase (codigo, nombre, region) values (669, 'Lamiaceae', 'San Francisco');
insert into clase (codigo, nombre, region) values (670, 'Cyperaceae', 'Wulan Haye');
insert into clase (codigo, nombre, region) values (671, 'Rosaceae', 'Xichangmen');
insert into clase (codigo, nombre, region) values (672, 'Asteraceae', 'Poxin');
insert into clase (codigo, nombre, region) values (673, 'Clavariaceae', 'Paraíso');
insert into clase (codigo, nombre, region) values (674, 'Sterculiaceae', 'Ciilat');
insert into clase (codigo, nombre, region) values (675, 'Uncertain Ascomycota Family', 'Haarlem');
insert into clase (codigo, nombre, region) values (676, 'Physciaceae', 'Jiangzao');
insert into clase (codigo, nombre, region) values (677, 'Mniaceae', 'Chengbei');
insert into clase (codigo, nombre, region) values (678, 'Collemataceae', 'Września');
insert into clase (codigo, nombre, region) values (679, 'Sphagnaceae', 'San Diego');
insert into clase (codigo, nombre, region) values (680, 'Aquifoliaceae', 'Chantilly');
insert into clase (codigo, nombre, region) values (681, 'Sapotaceae', 'Padangpanjang');
insert into clase (codigo, nombre, region) values (682, 'Malvaceae', 'Huaihe');
insert into clase (codigo, nombre, region) values (683, 'Pinaceae', 'Bzenec');
insert into clase (codigo, nombre, region) values (684, 'Malvaceae', 'Kirkton');
insert into clase (codigo, nombre, region) values (685, 'Polygonaceae', 'Juarez');
insert into clase (codigo, nombre, region) values (686, 'Grimmiaceae', 'Arraga');
insert into clase (codigo, nombre, region) values (687, 'Euphorbiaceae', 'Ubonratana');
insert into clase (codigo, nombre, region) values (688, 'Hydrophyllaceae', 'Lansing');
insert into clase (codigo, nombre, region) values (689, 'Pinaceae', 'Haiyu');
insert into clase (codigo, nombre, region) values (690, 'Ericaceae', 'Taphan Hin');
insert into clase (codigo, nombre, region) values (691, 'Cyperaceae', 'Natakoli');
insert into clase (codigo, nombre, region) values (692, 'Asteraceae', 'Uubulan');
insert into clase (codigo, nombre, region) values (693, 'Anacardiaceae', 'Íasmos');
insert into clase (codigo, nombre, region) values (694, 'Asteraceae', 'Manas');
insert into clase (codigo, nombre, region) values (695, 'Cyperaceae', 'Herne');
insert into clase (codigo, nombre, region) values (696, 'Ranunculaceae', 'Strazhitsa');
insert into clase (codigo, nombre, region) values (697, 'Brassicaceae', 'Houping');
insert into clase (codigo, nombre, region) values (698, 'Violaceae', 'Zakliczyn');
insert into clase (codigo, nombre, region) values (699, 'Brassicaceae', 'Golčův Jeníkov');
insert into clase (codigo, nombre, region) values (700, 'Mniaceae', 'Mikhnëvo');
insert into clase (codigo, nombre, region) values (701, 'Campanulaceae', 'Verrettes');
insert into clase (codigo, nombre, region) values (702, 'Asteraceae', 'Panjakent');
insert into clase (codigo, nombre, region) values (703, 'Asteraceae', 'Viškovci');
insert into clase (codigo, nombre, region) values (704, 'Asteraceae', 'Ashgabat');
insert into clase (codigo, nombre, region) values (705, 'Buddlejaceae', 'Kaliuda');
insert into clase (codigo, nombre, region) values (706, 'Alismataceae', 'Takum');
insert into clase (codigo, nombre, region) values (707, 'Bryaceae', 'Rambatan');
insert into clase (codigo, nombre, region) values (708, 'Malvaceae', 'Qingfenglin');
insert into clase (codigo, nombre, region) values (709, 'Cyperaceae', 'Linhares');
insert into clase (codigo, nombre, region) values (710, 'Acanthaceae', 'Minas de Matahambre');
insert into clase (codigo, nombre, region) values (711, 'Scrophulariaceae', 'Bulusari');
insert into clase (codigo, nombre, region) values (712, 'Rosaceae', 'Slobodnica');
insert into clase (codigo, nombre, region) values (713, 'Asteraceae', 'Tembilahan');
insert into clase (codigo, nombre, region) values (714, 'Fabaceae', 'Quetta');
insert into clase (codigo, nombre, region) values (715, 'Brassicaceae', 'Egvekinot');
insert into clase (codigo, nombre, region) values (716, 'Papaveraceae', 'Pangantocan');
insert into clase (codigo, nombre, region) values (717, 'Hydrangeaceae', 'Nirgua');
insert into clase (codigo, nombre, region) values (718, 'Gentianaceae', 'Kętrzyn');
insert into clase (codigo, nombre, region) values (719, 'Olacaceae', 'Bugis');
insert into clase (codigo, nombre, region) values (720, 'Ranunculaceae', 'Korisós');
insert into clase (codigo, nombre, region) values (721, 'Euphorbiaceae', 'Monterrey');
insert into clase (codigo, nombre, region) values (722, 'Limnanthaceae', 'Dawang');
insert into clase (codigo, nombre, region) values (723, 'Apiaceae', 'Šmartno pri Litiji');
insert into clase (codigo, nombre, region) values (724, 'Parmeliaceae', 'Ilioúpoli');
insert into clase (codigo, nombre, region) values (725, 'Rosaceae', 'Kolbudy');
insert into clase (codigo, nombre, region) values (726, 'Juncaceae', 'Kastsyukovichy');
insert into clase (codigo, nombre, region) values (727, 'Ectolechiaceae', 'Dearborn');
insert into clase (codigo, nombre, region) values (728, 'Hedwigiaceae', 'La Coipa');
insert into clase (codigo, nombre, region) values (729, 'Uncertain Ascomycota Family', 'Uppsala');
insert into clase (codigo, nombre, region) values (730, 'Poaceae', 'København');
insert into clase (codigo, nombre, region) values (731, 'Arecaceae', 'Gizel’');
insert into clase (codigo, nombre, region) values (732, 'Orchidaceae', 'Palcza');
insert into clase (codigo, nombre, region) values (733, 'Orchidaceae', 'Bethlehem');
insert into clase (codigo, nombre, region) values (734, 'Graphidaceae', 'Lityn');
insert into clase (codigo, nombre, region) values (735, 'Juncaceae', 'Yukuhashi');
insert into clase (codigo, nombre, region) values (736, 'Asteraceae', 'Puning');
insert into clase (codigo, nombre, region) values (737, 'Burmanniaceae', 'Xiexiong');
insert into clase (codigo, nombre, region) values (738, 'Cyperaceae', 'Wentugaole');
insert into clase (codigo, nombre, region) values (739, 'Poaceae', 'Göteborg');
insert into clase (codigo, nombre, region) values (740, 'Brassicaceae', 'Ḩadīdah');
insert into clase (codigo, nombre, region) values (741, 'Asteraceae', 'Vathýlakkos');
insert into clase (codigo, nombre, region) values (742, 'Poaceae', 'Cinco Saltos');
insert into clase (codigo, nombre, region) values (743, 'Polygonaceae', 'Diaoling');
insert into clase (codigo, nombre, region) values (744, 'Myrtaceae', 'Lashkar Gāh');
insert into clase (codigo, nombre, region) values (745, 'Cactaceae', 'Xinglong');
insert into clase (codigo, nombre, region) values (746, 'Asteraceae', 'Dębno');
insert into clase (codigo, nombre, region) values (747, 'Sphagnaceae', 'Czarna');
insert into clase (codigo, nombre, region) values (748, 'Asteraceae', 'Yangdian');
insert into clase (codigo, nombre, region) values (749, 'Asteraceae', 'Rajadesa');
insert into clase (codigo, nombre, region) values (750, 'Juncaceae', 'Danzi');
insert into clase (codigo, nombre, region) values (751, 'Asteraceae', 'Xihongmen');
insert into clase (codigo, nombre, region) values (752, 'Ericaceae', 'Nelas');
insert into clase (codigo, nombre, region) values (753, 'Salicaceae', 'Suka Makmue');
insert into clase (codigo, nombre, region) values (754, 'Myrtaceae', 'Yedun');
insert into clase (codigo, nombre, region) values (755, 'Asteraceae', 'Flin Flon');
insert into clase (codigo, nombre, region) values (756, 'Cyperaceae', 'Hexiangqiao');
insert into clase (codigo, nombre, region) values (757, 'Rubiaceae', 'Linjiang');
insert into clase (codigo, nombre, region) values (758, 'Polygonaceae', 'Paucar');
insert into clase (codigo, nombre, region) values (759, 'Campanulaceae', 'Anilao');
insert into clase (codigo, nombre, region) values (760, 'Asteraceae', 'Beiwucha');
insert into clase (codigo, nombre, region) values (761, 'Gentianaceae', 'Argir');
insert into clase (codigo, nombre, region) values (762, 'Teloschistaceae', 'Staroutkinsk');
insert into clase (codigo, nombre, region) values (763, 'Gunneraceae', 'Mertani');
insert into clase (codigo, nombre, region) values (764, 'Fabaceae', 'Libiąż');
insert into clase (codigo, nombre, region) values (765, 'Verbenaceae', 'Suci Kaler');
insert into clase (codigo, nombre, region) values (766, 'Boraginaceae', 'Santa Cruz');
insert into clase (codigo, nombre, region) values (767, 'Orchidaceae', 'Sidi Lamine');
insert into clase (codigo, nombre, region) values (768, 'Amaranthaceae', 'Maomiaoji');
insert into clase (codigo, nombre, region) values (769, 'Dilleniaceae', 'Chagou');
insert into clase (codigo, nombre, region) values (770, 'Liliaceae', 'Nagorsk');
insert into clase (codigo, nombre, region) values (771, 'Orchidaceae', 'Lyon');
insert into clase (codigo, nombre, region) values (772, 'Poaceae', 'Sedatigede');
insert into clase (codigo, nombre, region) values (773, 'Asteraceae', 'Dos Hermanas');
insert into clase (codigo, nombre, region) values (774, 'Urticaceae', 'Bagadó');
insert into clase (codigo, nombre, region) values (775, 'Lecanoraceae', 'Stalbe');
insert into clase (codigo, nombre, region) values (776, 'Boraginaceae', 'Igarra');
insert into clase (codigo, nombre, region) values (777, 'Pyrenulaceae', 'Tyoply Stan');
insert into clase (codigo, nombre, region) values (778, 'Lycopodiaceae', 'Geneina');
insert into clase (codigo, nombre, region) values (779, 'Alismataceae', 'Bantilan');
insert into clase (codigo, nombre, region) values (780, 'Brassicaceae', 'Sanguanzhai');
insert into clase (codigo, nombre, region) values (781, 'Verbenaceae', 'Kerek');
insert into clase (codigo, nombre, region) values (782, 'Polygonaceae', 'Anggana');
insert into clase (codigo, nombre, region) values (783, 'Arthoniaceae', 'Donghai');
insert into clase (codigo, nombre, region) values (784, 'Convolvulaceae', 'Tchaourou');
insert into clase (codigo, nombre, region) values (785, 'Polytrichaceae', 'Majiao');
insert into clase (codigo, nombre, region) values (786, 'Dioscoreaceae', 'Havre-Saint-Pierre');
insert into clase (codigo, nombre, region) values (787, 'Arecaceae', 'Rozkishne');
insert into clase (codigo, nombre, region) values (788, 'Aristolochiaceae', 'Bremerhaven');
insert into clase (codigo, nombre, region) values (789, 'Poaceae', 'El Retorno');
insert into clase (codigo, nombre, region) values (790, 'Parmeliaceae', 'Aparecida do Taboado');
insert into clase (codigo, nombre, region) values (791, 'Asteraceae', 'Malimaneek');
insert into clase (codigo, nombre, region) values (792, 'Solanaceae', 'Wiwilí');
insert into clase (codigo, nombre, region) values (793, 'Lamiaceae', 'Jiangfang');
insert into clase (codigo, nombre, region) values (794, 'Poaceae', 'Qiaotou');
insert into clase (codigo, nombre, region) values (795, 'Scrophulariaceae', 'Yoro');
insert into clase (codigo, nombre, region) values (796, 'Fabaceae', 'Čajniče');
insert into clase (codigo, nombre, region) values (797, 'Orchidaceae', 'Tirlyanskiy');
insert into clase (codigo, nombre, region) values (798, 'Viscaceae', 'Darovskoy');
insert into clase (codigo, nombre, region) values (799, 'Chenopodiaceae', 'Moa');
insert into clase (codigo, nombre, region) values (800, 'Rhamnaceae', 'Zaragoza');
insert into clase (codigo, nombre, region) values (801, 'Lamiaceae', 'Colonia Nicolich');
insert into clase (codigo, nombre, region) values (802, 'Verbenaceae', 'Titao');
insert into clase (codigo, nombre, region) values (803, 'Liliaceae', 'Masinloc');
insert into clase (codigo, nombre, region) values (804, 'Iridaceae', 'Changlin');
insert into clase (codigo, nombre, region) values (805, 'Fabaceae', 'Tríkeri');
insert into clase (codigo, nombre, region) values (806, 'Asteraceae', 'Peremyshl’');
insert into clase (codigo, nombre, region) values (807, 'Fabaceae', 'Panbang');
insert into clase (codigo, nombre, region) values (808, 'Cuscutaceae', 'Garahan');
insert into clase (codigo, nombre, region) values (809, 'Leskeaceae', 'Ad Dabbah');
insert into clase (codigo, nombre, region) values (810, 'Rosaceae', 'Lumbac');
insert into clase (codigo, nombre, region) values (811, 'Liliaceae', 'Beberibe');
insert into clase (codigo, nombre, region) values (812, 'Asteraceae', 'Aborlan');
insert into clase (codigo, nombre, region) values (813, 'Asteraceae', 'Daji');
insert into clase (codigo, nombre, region) values (814, 'Clusiaceae', 'Xianghua');
insert into clase (codigo, nombre, region) values (815, 'Gesneriaceae', 'Nongba');
insert into clase (codigo, nombre, region) values (816, 'Fabaceae', 'Czudec');
insert into clase (codigo, nombre, region) values (817, 'Juncaceae', 'Karanggedang');
insert into clase (codigo, nombre, region) values (818, 'Rosaceae', 'Huixian Chengguanzhen');
insert into clase (codigo, nombre, region) values (819, 'Asclepiadaceae', 'Francisco Beltrão');
insert into clase (codigo, nombre, region) values (820, 'Urticaceae', '‘Alāqahdārī Kirān wa Munjān');
insert into clase (codigo, nombre, region) values (821, 'Cuscutaceae', 'Nalsian Norte');
insert into clase (codigo, nombre, region) values (822, 'Ophioglossaceae', 'Xiaoxiang');
insert into clase (codigo, nombre, region) values (823, 'Tiliaceae', 'Kiambu');
insert into clase (codigo, nombre, region) values (824, 'Fumariaceae', 'Igarapé Miri');
insert into clase (codigo, nombre, region) values (825, 'Apiaceae', 'Yirga ‘Alem');
insert into clase (codigo, nombre, region) values (826, 'Solanaceae', 'Czerniewice');
insert into clase (codigo, nombre, region) values (827, 'Rubiaceae', 'Rozsypne');
insert into clase (codigo, nombre, region) values (828, 'Cyperaceae', 'Sergiyev Posad');
insert into clase (codigo, nombre, region) values (829, 'Liliaceae', 'Troitskoye');
insert into clase (codigo, nombre, region) values (830, 'Fabaceae', 'Liberta');
insert into clase (codigo, nombre, region) values (831, 'Fabaceae', 'Bertioga');
insert into clase (codigo, nombre, region) values (832, 'Asteraceae', 'Famaillá');
insert into clase (codigo, nombre, region) values (833, 'Ramalinaceae', 'Uthai Thani');
insert into clase (codigo, nombre, region) values (834, 'Poaceae', 'Police nad Metují');
insert into clase (codigo, nombre, region) values (835, 'Poaceae', 'Shenshu');
insert into clase (codigo, nombre, region) values (836, 'Fabaceae', 'Linggamanik');
insert into clase (codigo, nombre, region) values (837, 'Pyrenulaceae', 'Brejo da Madre de Deus');
insert into clase (codigo, nombre, region) values (838, 'Iridaceae', 'Cimongkor');
insert into clase (codigo, nombre, region) values (839, 'Papaveraceae', 'Taotang');
insert into clase (codigo, nombre, region) values (840, 'Anacardiaceae', 'Dananyu');
insert into clase (codigo, nombre, region) values (841, 'Primulaceae', 'Sidaurip');
insert into clase (codigo, nombre, region) values (842, 'Caryophyllaceae', 'Zabukovica');
insert into clase (codigo, nombre, region) values (843, 'Hydrophyllaceae', 'Bakhmach');
insert into clase (codigo, nombre, region) values (844, 'Brassicaceae', 'Rosmalen');
insert into clase (codigo, nombre, region) values (845, 'Asteraceae', 'Khuzhir');
insert into clase (codigo, nombre, region) values (846, 'Rosaceae', 'Valdemārpils');
insert into clase (codigo, nombre, region) values (847, 'Lecanoraceae', 'Erdaojiang');
insert into clase (codigo, nombre, region) values (848, 'Valerianaceae', 'Tianchi');
insert into clase (codigo, nombre, region) values (849, 'Isoetaceae', 'Chicago');
insert into clase (codigo, nombre, region) values (850, 'Crassulaceae', 'Genyem');
insert into clase (codigo, nombre, region) values (851, 'Parmeliaceae', 'Agraharam');
insert into clase (codigo, nombre, region) values (852, 'Boraginaceae', 'Czarna');
insert into clase (codigo, nombre, region) values (853, 'Berberidaceae', 'Yubileynyy');
insert into clase (codigo, nombre, region) values (854, 'Araliaceae', 'Aguisan');
insert into clase (codigo, nombre, region) values (855, 'Loasaceae', 'Sada');
insert into clase (codigo, nombre, region) values (856, 'Campanulaceae', 'Antony');
insert into clase (codigo, nombre, region) values (857, 'Asteraceae', 'Ghāro');
insert into clase (codigo, nombre, region) values (858, 'Cyperaceae', 'Ardazubre');
insert into clase (codigo, nombre, region) values (859, 'Crassulaceae', 'Taposan');
insert into clase (codigo, nombre, region) values (860, 'Flacourtiaceae', 'Wanshi');
insert into clase (codigo, nombre, region) values (861, 'Apiaceae', 'Sedlarevo');
insert into clase (codigo, nombre, region) values (862, 'Asteraceae', 'Yangjiaqiao');
insert into clase (codigo, nombre, region) values (863, 'Poaceae', 'Ambatondrazaka');
insert into clase (codigo, nombre, region) values (864, 'Asteraceae', 'Pavlovskaya');
insert into clase (codigo, nombre, region) values (865, 'Asteraceae', 'Xiaoruo');
insert into clase (codigo, nombre, region) values (866, 'Lamiaceae', 'Paccha');
insert into clase (codigo, nombre, region) values (867, 'Buxaceae', 'Inari');
insert into clase (codigo, nombre, region) values (868, 'Crassulaceae', 'Zebrzydowice');
insert into clase (codigo, nombre, region) values (869, 'Asteraceae', 'Magog');
insert into clase (codigo, nombre, region) values (870, 'Primulaceae', 'Nanxinxiang');
insert into clase (codigo, nombre, region) values (871, 'Cyperaceae', 'Dazhou');
insert into clase (codigo, nombre, region) values (872, 'Fabaceae', 'Dudchany');
insert into clase (codigo, nombre, region) values (873, 'Orchidaceae', 'Phetchabun');
insert into clase (codigo, nombre, region) values (874, 'Brassicaceae', 'Curiapo');
insert into clase (codigo, nombre, region) values (875, 'Cactaceae', 'Sandata');
insert into clase (codigo, nombre, region) values (876, 'Callitrichaceae', 'Siparia');
insert into clase (codigo, nombre, region) values (877, 'Selaginellaceae', 'Carvalhinho');
insert into clase (codigo, nombre, region) values (878, 'Onagraceae', 'Várzea');
insert into clase (codigo, nombre, region) values (879, 'Fabaceae', 'Pradera');
insert into clase (codigo, nombre, region) values (880, 'Polypodiaceae', 'Sotteville-lès-Rouen');
insert into clase (codigo, nombre, region) values (881, 'Liliaceae', 'Zašová');
insert into clase (codigo, nombre, region) values (882, 'Rhamnaceae', 'Santa Teresa');
insert into clase (codigo, nombre, region) values (883, 'Poaceae', 'Rejoso');
insert into clase (codigo, nombre, region) values (884, 'Asteraceae', 'Dahuang');
insert into clase (codigo, nombre, region) values (885, 'Bryaceae', 'Erbil');
insert into clase (codigo, nombre, region) values (886, 'Verrucariaceae', 'Osveya');
insert into clase (codigo, nombre, region) values (887, 'Asteraceae', 'Nong Khai');
insert into clase (codigo, nombre, region) values (888, 'Saxifragaceae', 'Warnes');
insert into clase (codigo, nombre, region) values (889, 'Papaveraceae', 'Taoling');
insert into clase (codigo, nombre, region) values (890, 'Fagaceae', 'Heshui');
insert into clase (codigo, nombre, region) values (891, 'Lentibulariaceae', 'Bansko');
insert into clase (codigo, nombre, region) values (892, 'Polemoniaceae', 'Krzemieniewo');
insert into clase (codigo, nombre, region) values (893, 'Papaveraceae', 'Leicheng');
insert into clase (codigo, nombre, region) values (894, 'Fabaceae', 'Plaju');
insert into clase (codigo, nombre, region) values (895, 'Bignoniaceae', 'La Calera');
insert into clase (codigo, nombre, region) values (896, 'Polytrichaceae', 'Dame-Marie');
insert into clase (codigo, nombre, region) values (897, 'Cucurbitaceae', 'Dortmund');
insert into clase (codigo, nombre, region) values (898, 'Saxifragaceae', 'Estique');
insert into clase (codigo, nombre, region) values (899, 'Scrophulariaceae', 'Lepaterique');
insert into clase (codigo, nombre, region) values (900, 'Fumariaceae', 'Dongmaku');
insert into clase (codigo, nombre, region) values (901, 'Fabaceae', 'Krong Pi Nang');
insert into clase (codigo, nombre, region) values (902, 'Poaceae', 'Houjia');
insert into clase (codigo, nombre, region) values (903, 'Rubiaceae', 'Betong');
insert into clase (codigo, nombre, region) values (904, 'Fabaceae', 'Cambridge');
insert into clase (codigo, nombre, region) values (905, 'Caryophyllaceae', 'Krosno');
insert into clase (codigo, nombre, region) values (906, 'Brassicaceae', 'Is');
insert into clase (codigo, nombre, region) values (907, 'Asteraceae', 'Longtian');
insert into clase (codigo, nombre, region) values (908, 'Pyrolaceae', 'Donskoy');
insert into clase (codigo, nombre, region) values (909, 'Orchidaceae', 'Quisqueya');
insert into clase (codigo, nombre, region) values (910, 'Poaceae', 'Atuntaqui');
insert into clase (codigo, nombre, region) values (911, 'Marantaceae', 'Hitura');
insert into clase (codigo, nombre, region) values (912, 'Ericaceae', 'Žabljak');
insert into clase (codigo, nombre, region) values (913, 'Asteraceae', 'Ayní');
insert into clase (codigo, nombre, region) values (914, 'Physciaceae', 'Kochetok');
insert into clase (codigo, nombre, region) values (915, 'Apocynaceae', 'Ouro Preto');
insert into clase (codigo, nombre, region) values (916, 'Hydrophyllaceae', 'Mingora');
insert into clase (codigo, nombre, region) values (917, 'Primulaceae', 'Türkmenbaşy');
insert into clase (codigo, nombre, region) values (918, 'Cupressaceae', 'Maastricht');
insert into clase (codigo, nombre, region) values (919, 'Scrophulariaceae', 'Luoqiao');
insert into clase (codigo, nombre, region) values (920, 'Buddlejaceae', 'Kusak');
insert into clase (codigo, nombre, region) values (921, 'Asteraceae', 'Potrero Grande');
insert into clase (codigo, nombre, region) values (922, 'Orobanchaceae', 'Kyaka');
insert into clase (codigo, nombre, region) values (923, 'Rosaceae', 'Mporokoso');
insert into clase (codigo, nombre, region) values (924, 'Asteraceae', 'Yantang');
insert into clase (codigo, nombre, region) values (925, 'Orchidaceae', 'Nagrak');
insert into clase (codigo, nombre, region) values (926, 'Fabaceae', 'Esperanza');
insert into clase (codigo, nombre, region) values (927, 'Campanulaceae', 'Nunhala');
insert into clase (codigo, nombre, region) values (928, 'Pottiaceae', 'Ngepoh Kidul');
insert into clase (codigo, nombre, region) values (929, 'Asteraceae', 'Koran');
insert into clase (codigo, nombre, region) values (930, 'Sapindaceae', 'Tanggulangin');
insert into clase (codigo, nombre, region) values (931, 'Annonaceae', 'Quinta de Valadares');
insert into clase (codigo, nombre, region) values (932, 'Physciaceae', 'Mariestad');
insert into clase (codigo, nombre, region) values (933, 'Orchidaceae', 'Ngulahan');
insert into clase (codigo, nombre, region) values (934, 'Poaceae', 'Madrid');
insert into clase (codigo, nombre, region) values (935, 'Gyalectaceae', 'Sondo');
insert into clase (codigo, nombre, region) values (936, 'Gesneriaceae', 'Gabasumdo');
insert into clase (codigo, nombre, region) values (937, 'Parmeliaceae', 'Pampas');
insert into clase (codigo, nombre, region) values (938, 'Rutaceae', 'Cilolongokan');
insert into clase (codigo, nombre, region) values (939, 'Apiaceae', 'Salvacion');
insert into clase (codigo, nombre, region) values (940, 'Hymenophyllaceae', 'Benhong');
insert into clase (codigo, nombre, region) values (941, 'Parmeliaceae', 'Balading');
insert into clase (codigo, nombre, region) values (942, 'Asteraceae', 'Kauswagan');
insert into clase (codigo, nombre, region) values (943, 'Liliaceae', 'Khoronk’');
insert into clase (codigo, nombre, region) values (944, 'Ranunculaceae', 'Osekovo');
insert into clase (codigo, nombre, region) values (945, 'Lecideaceae', 'Suva Reka');
insert into clase (codigo, nombre, region) values (946, 'Rosaceae', 'Azun Atme');
insert into clase (codigo, nombre, region) values (947, 'Goodeniaceae', 'Bamnet Narong');
insert into clase (codigo, nombre, region) values (948, 'Lecanoraceae', 'Mshinskaya');
insert into clase (codigo, nombre, region) values (949, 'Fabaceae', 'Irecê');
insert into clase (codigo, nombre, region) values (950, 'Malvaceae', 'Koesan');
insert into clase (codigo, nombre, region) values (951, 'Brassicaceae', 'Utrecht (stad)');
insert into clase (codigo, nombre, region) values (952, 'Asteraceae', 'Mae Sai');
insert into clase (codigo, nombre, region) values (953, 'Saxifragaceae', 'Marinilla');
insert into clase (codigo, nombre, region) values (954, 'Encalyptaceae', 'Sucre');
insert into clase (codigo, nombre, region) values (955, 'Cactaceae', 'Canomoy');
insert into clase (codigo, nombre, region) values (956, 'Asteraceae', 'Plaza de Caisán');
insert into clase (codigo, nombre, region) values (957, 'Orchidaceae', 'Itbayat');
insert into clase (codigo, nombre, region) values (958, 'Hydrangeaceae', 'Kapatagan');
insert into clase (codigo, nombre, region) values (959, 'Lecanoraceae', 'Brive-la-Gaillarde');
insert into clase (codigo, nombre, region) values (960, 'Asteraceae', 'Chervonopartyzans’k');
insert into clase (codigo, nombre, region) values (961, 'Brassicaceae', 'Sinisian');
insert into clase (codigo, nombre, region) values (962, 'Brassicaceae', 'Xinyu');
insert into clase (codigo, nombre, region) values (963, 'Solanaceae', 'Monastirákion');
insert into clase (codigo, nombre, region) values (964, 'Boraginaceae', 'Changxing');
insert into clase (codigo, nombre, region) values (965, 'Poaceae', 'Puerto Rico');
insert into clase (codigo, nombre, region) values (966, 'Fabaceae', 'Krasnogvardeyets');
insert into clase (codigo, nombre, region) values (967, 'Caryophyllaceae', 'Salas');
insert into clase (codigo, nombre, region) values (968, 'Hydrophyllaceae', 'Ramaram');
insert into clase (codigo, nombre, region) values (969, 'Acanthaceae', 'Täby');
insert into clase (codigo, nombre, region) values (970, 'Apiaceae', 'Solna');
insert into clase (codigo, nombre, region) values (971, 'Parmeliaceae', 'Yangjiaping');
insert into clase (codigo, nombre, region) values (972, 'Agavaceae', 'Hats’avan');
insert into clase (codigo, nombre, region) values (973, 'Rubiaceae', 'Solčava');
insert into clase (codigo, nombre, region) values (974, 'Asteraceae', 'Baltiysk');
insert into clase (codigo, nombre, region) values (975, 'Poaceae', 'Tyre');
insert into clase (codigo, nombre, region) values (976, 'Liliaceae', 'Rybnoye');
insert into clase (codigo, nombre, region) values (977, 'Polemoniaceae', 'Saribudolok');
insert into clase (codigo, nombre, region) values (978, 'Valerianaceae', 'Wawu');
insert into clase (codigo, nombre, region) values (979, 'Cuscutaceae', 'Villa Altagracia');
insert into clase (codigo, nombre, region) values (980, 'Asteraceae', 'Agalteca');
insert into clase (codigo, nombre, region) values (981, 'Ranunculaceae', 'Naranjo');
insert into clase (codigo, nombre, region) values (982, 'Poaceae', 'Taiping');
insert into clase (codigo, nombre, region) values (983, 'Rosaceae', 'Xiniu');
insert into clase (codigo, nombre, region) values (984, 'Dryopteridaceae', 'Ludwin');
insert into clase (codigo, nombre, region) values (985, 'Poaceae', 'Hernández');
insert into clase (codigo, nombre, region) values (986, 'Asteraceae', 'Tío Pujio');
insert into clase (codigo, nombre, region) values (987, 'Ranunculaceae', 'Anh Son');
insert into clase (codigo, nombre, region) values (988, 'Fagaceae', 'Krupka');
insert into clase (codigo, nombre, region) values (989, 'Poaceae', 'Syriam');
insert into clase (codigo, nombre, region) values (990, 'Liliaceae', 'Duobao');
insert into clase (codigo, nombre, region) values (991, 'Asteraceae', 'Lancaster');
insert into clase (codigo, nombre, region) values (992, 'Boraginaceae', 'Várzea');
insert into clase (codigo, nombre, region) values (993, 'Rosaceae', 'Štěchovice');
insert into clase (codigo, nombre, region) values (994, 'Brassicaceae', 'Concepción');
insert into clase (codigo, nombre, region) values (995, 'Orchidaceae', 'Windusakti Hilir');
insert into clase (codigo, nombre, region) values (996, 'Caryophyllaceae', 'Mersa Matruh');
insert into clase (codigo, nombre, region) values (997, 'Fabaceae', 'Swellendam');
insert into clase (codigo, nombre, region) values (998, 'Hydrophyllaceae', 'Kakogawachō-honmachi');
insert into clase (codigo, nombre, region) values (999, 'Scrophulariaceae', 'Xiqiao');
insert into clase (codigo, nombre, region) values (1000, 'Brassicaceae', 'Uglegorsk');
