insert into Pais (id, nombre) values (1, 'China');
insert into Pais (id, nombre) values (2, 'Brazil');
insert into Pais (id, nombre) values (3, 'United States');
insert into Pais (id, nombre) values (4, 'Peru');
insert into Pais (id, nombre) values (5, 'Thailand');
insert into Pais (id, nombre) values (6, 'Monaco');
insert into Pais (id, nombre) values (7, 'Colombia');
insert into Pais (id, nombre) values (8, 'Venezuela');
insert into Pais (id, nombre) values (9, 'Portugal');
insert into Pais (id, nombre) values (10, 'Croatia');
insert into Pais (id, nombre) values (11, 'Philippines');
insert into Pais (id, nombre) values (12, 'Maldives');
insert into Pais (id, nombre) values (13, 'Indonesia');
insert into Pais (id, nombre) values (14, 'Botswana');
insert into Pais (id, nombre) values (15, 'Russia');
insert into Pais (id, nombre) values (16, 'Japan');
insert into Pais (id, nombre) values (17, 'Poland');
insert into Pais (id, nombre) values (18, 'Ethiopia');
insert into Pais (id, nombre) values (19, 'Syria');
insert into Pais (id, nombre) values (20, 'Iran');
insert into Pais (id, nombre) values (21, 'Cuba');
insert into Pais (id, nombre) values (22, 'Mongolia');
insert into Pais (id, nombre) values (23, 'Bangladesh');
insert into Pais (id, nombre) values (24, 'France');
insert into Pais (id, nombre) values (25, 'Ecuador');

